export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const STOP_LOADING = 'USER_LOADING_STOP';

export const Questions = {
	RAISE     : 'RAISE_QUESTION',
	RAISED    : 'QUESTION_RAISED',
	ACCEPT    : 'ACCEPT_QUESTION',
	ACCEPTED  : 'QUESTION_ACCEPTED',
	CANCEL    : 'CANCEL_QUESTION',
	CANCELLED : 'QUESTION_CANCELLED',
	REJECT    : 'REJECT_QUESTION',
	REJECTED  : 'QUESTION_REJECTED',
	END       : 'END_QUESTION',
	ENDED     : 'QUESTION_ENDED'
};

export const Rooms = {
	GETALL    : 'ROOMS_GETALL',
	ADDONE    : 'ROOMS_ADDONE',
	REMOVEONE : 'ROOMS_REMOVEONE',
	REMOVEALL : 'ROOMS_REMOVEALL'
};
